name: PlayerBounties
version: 1.0.2-Release
api-version: 1.17
author: StivenFocs
main: cloud.stivenfocs.PlayerBounties.Loader
depend: [Vault]
description: "Apply a bounty to a player IF YOU WANT HIM DEAD"
commands:
    playerbounties:
        aliases: [pb,bounty]
permission:
    playerbounties.bounty:
        default: true
    playerbounties.claim:
        default: true
    playerbounties.admin:
        default: op